Repository cdm-processors/cdm-devkit, pull requests merged in 2023-02, with the labels that each got.

#4 Fixes for universal part of assembler
  cocas/assembler.py
  cocas/default_code_segments.py
  cocas/generated/AsmLexer.py
  cocas/grammar/AsmLexer.g4
  cocas/linker.py
  cocas/main.py
  cocas/object_module.py
  cocas/targets/cdm8e/__init__.py
  cocas/targets/cdm8e/code_segments.py
  cocas/targets/cdm8e/target_instructions.py
  examples/cdm8e/address_test.asm
  examples/cdm8e/save_restore.asm
  examples/cdm8e/test_every_goto.asm
Labels: fix

#12 Create VS Code extension supporting several languages
  vscode-cdm-extension/.gitignore
  vscode-cdm-extension/.vscode/launch.json
  vscode-cdm-extension/.vscodeignore
  vscode-cdm-extension/LICENSE
  vscode-cdm-extension/README.md
  vscode-cdm-extension/icon.png
  vscode-cdm-extension/languages/assembly-language-configuration.json
  vscode-cdm-extension/languages/microcode-language-configuration.json
  vscode-cdm-extension/package.json
  vscode-cdm-extension/snippets/cdm-assembly-snippets.json
  vscode-cdm-extension/syntaxes/cdm-microcode.tmLanguage.json
  vscode-cdm-extension/syntaxes/cdm16-assembly.tmLanguage.json
  vscode-cdm-extension/syntaxes/cdm8-assembly.tmLanguage.json
  vscode-cdm-extension/syntaxes/cdm8e-assembly.tmLanguage.json
Labels: enhancement

#6 Fix banked memory visuals
  logisim/logisim-banked-memory/.gitignore
  logisim/logisim-banked-memory/build.gradle
  logisim/logisim-banked-memory/src/main/java/org/cdm/logisim/memory/BankedRAM.java
  logisim/logisim-banked-memory/src/main/java/org/cdm/logisim/memory/BankedROM.java
Labels: fix

#2 Repository enhancements
  .github/workflows/release.yml
  Makefile
  README.md
  docs/cdm8e/.gitignore
  docs/cdm8e/instruction-description.tex
  docs/cdm8e/logo.png
  docs/cdm8e/main.pdf
  docs/cdm8e/main.tex
  docs/cdm8e/ol-softwaremanual.cls
  docs/getting-started.md
  docs/images/cdm16_vn_minimal.PNG
  docs/images/cdm8_hv.png
  docs/images/cdm8_vn.png
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement

#13 CdM-16 updates
  logisim/cdm16/cdm16.circ
  logisim/cdm16/microcode/cdm16_decoder.def
Labels: enhancement

#15 Add CdM-16 target for assembler
  cocas/targets/cdm16/__init__.py
  cocas/targets/cdm16/code_segments.py
  cocas/targets/cdm16/standard.mlb
  cocas/targets/cdm16/target_instructions.py
Labels: enhancement

#18 Add AutoRAM
  logisim/logisim-banked-memory/src/main/java/org/cdm/logisim/memory/BankedMem.java
  logisim/logisim-banked-memory/src/main/java/org/cdm/logisim/memory/BankedMemState.java
  logisim/logisim-banked-memory/src/main/java/org/cdm/logisim/memory/BankedRAM.java
  logisim/logisim-banked-memory/src/main/java/org/cdm/logisim/memory/BankedROM.java
  logisim/logisim-banked-memory/src/main/java/org/cdm/logisim/memory/BankedRomAttributes.java
Labels: enhancement

#16 Fixes and relative branches for CdM-16
  cocas/assembler.py
  cocas/ast_builder.py
  cocas/ast_nodes.py
  cocas/code_block.py
  cocas/default_instructions.py
  cocas/linker.py
  cocas/main.py
  cocas/object_module.py
  cocas/targets/cdm16/code_segments.py
  cocas/targets/cdm16/target_instructions.py
  cocas/targets/cdm8e/code_segments.py
  cocas/targets/cdm8e/target_instructions.py
Labels: enhancement, fix

#17 Update cdm16 syntax highlighting
  vscode-cdm-extension/syntaxes/cdm16-assembly.tmLanguage.json
Labels: fix

#19 CdM-16 startup sequence
  cocas/targets/cdm16/target_instructions.py
  docs/cdm16/cdm16-overview.md
  docs/getting-started.md
  logisim/cdm16/cdm16.circ
  logisim/cdm16/microcode/cdm16_decoder.def
  vscode-cdm-extension/syntaxes/cdm16-assembly.tmLanguage.json
Labels: enhancement

#22 Fix jsr instruction in CdM-16
  cocas/targets/cdm16/code_segments.py
  cocas/targets/cdm16/target_instructions.py
  logisim/cdm16/cdm16.circ
  logisim/cdm16/microcode/cdm16_decoder.def
Labels: fix
