Repository cdm-processors/cdm-devkit, pull requests merged in 2023-03, with the labels that each got.

#26 Another fixes for assembler
  cocas/code_block.py
  cocas/targets/cdm16/code_segments.py
  cocas/targets/cdm16/target_instructions.py
  vscode-cdm-extension/syntaxes/cdm16-assembly.tmLanguage.json
Labels: enhancement, fix

#28 Rework immediate value handling
  cocas/targets/cdm16/code_segments.py
  cocas/targets/cdm16/target_instructions.py
  docs/cdm16/cdm16-overview.md
  logisim/cdm16/cdm16.circ
  logisim/cdm16/microcode/cdm16_decoder.def
Labels: documentation, fix

#31 Fix very long cycles and if constructions didn't work with CdM-8e
  cocas/targets/cdm8e/code_segments.py
Labels: fix

#25 Presentation for 1st year students
  docs/cdm16/cdm16.pptx
Labels: documentation

#27 Implement new testing system
  outdated/tester/main.py
  outdated/tester/runners.py
  outdated/tester/state.py
  outdated/tests/cdm8e/fib.py
  outdated/tests/cdm8e/hs.py
  outdated/tests/cdm8e/if.py
  outdated/tests/cdm8e/ldi.py
  outdated/tests/cdm8e/long_jump.py
  outdated/tests/cdm8e/memory.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/factory/__init__.py
  tests/factory/circuit_state/__init__.py
  tests/factory/circuit_state/memory.py
  tests/factory/circuit_state/state.py
  tests/factory/collector.py
  tests/factory/results.py
  tests/factory/tools.py
  tests/resources/cdm16/example/program.asm
  tests/resources/cdm16/example/state.yaml
  tests/resources/cdm8e/conditions/program.asm
  tests/resources/cdm8e/conditions/state.yaml
  tests/resources/cdm8e/fibonacci/program.asm
  tests/resources/cdm8e/fibonacci/state.yaml
  tests/resources/cdm8e/hs/program.asm
  tests/resources/cdm8e/hs/state.yaml
  tests/resources/cdm8e/ldi/program.asm
  tests/resources/cdm8e/ldi/state.yaml
  tests/resources/cdm8e/long_jump/program.asm
  tests/resources/cdm8e/long_jump/state.yaml
  tests/resources/cdm8e/memory/program.asm
  tests/resources/cdm8e/memory/state.yaml
  tests/test_emulators.py
Labels: utility

#32 Add addsp with register for CdM-16
  cocas/targets/cdm16/target_instructions.py
  docs/cdm16/cdm16-overview.md
  logisim/cdm16/cdm16.circ
  logisim/cdm16/microcode/cdm16_decoder.def
Labels: enhancement

#34 Fix ugly print on linker errors
  cocas/main.py
Labels: fix

#33 Fix overlapping sections with 0 size
  cocas/linker.py
Labels: fix
