Repository cdm-processors/cdm-devkit, pull requests merged in 2025-02, with the labels that each got.

#86 Fix BindError in `cocoemu-server` and `logisim-debugger`
  cdp-java/src/main/java/org/cdm/debug/server/Server.java
  logisim/logisim-debugger/src/main/java/org/cdm/logisim/debugger/server/Server.java
Labels: fix

#87 VS Code Extension documentation
  README.md
  docs/README.md
  docs/assembly-templates.md
  docs/getting-started.md
  docs/guides/1-installing.md
  docs/guides/2-extension-overview.md
  docs/guides/3-setting-up-project.md
  docs/guides/4-debugging.md
  docs/guides/5-setting-up-logisim.md
  docs/guides/6-debugging-in-logisim.md
  docs/guides/7-using-cli.md
  docs/guides/8-external-build-systems.md
  docs/guides/9-using-python-environments.md
  docs/images/logisim_debugger.png
  docs/images/vscode_debug_interface.png
  docs/quickstart.md
Labels: documentation

#81 Emulator support for VS Code extension
  vscode-cdm-extension/README.md
  vscode-cdm-extension/package.json
  vscode-cdm-extension/src/commands/bootstrap/configurations.ts
  vscode-cdm-extension/src/commands/bootstrap/index.ts
  vscode-cdm-extension/src/commands/bootstrap/picks.ts
  vscode-cdm-extension/src/debug/runtime/emulator.ts
  vscode-cdm-extension/src/debug/runtime/environment.ts
  vscode-cdm-extension/src/debug/runtime/external.ts
  vscode-cdm-extension/src/debug/runtime/index.ts
  vscode-cdm-extension/src/debug/session.ts
  vscode-cdm-extension/src/stdlib.ts
  vscode-cdm-extension/src/tasks/providers.ts
Labels: enhancement
